name 'iptables'
maintainer 'Jeyashree Deepika'
maintainer_email 'jeyashreedeepika.s@tcs.com'
license 'all_rights'
description 'Installs/Configures iptables'
long_description 'Installs/Configures iptables'
version '0.1.0'
